### ISSUE TITLE
This repository is empty.

### ISSUE THREAD

**Issue by ChaituVR** [abhisekp/how-to-npm#1]
why is it empty???? :P

**Comment by abhisekp** [comment]
@ChaituVR LOL. coz it's supposed to be empty. Check https://github.com/npm/how-to-npm

**Comment by ChaituVR** [comment]
we don't need to add a repo right?

**Comment by abhisekp** [comment]
@ChaituVR nope! Just in case I had to push something to the repo.

**Comment by ChaituVR** [comment]
Thank you .. I didn't get it ;) ok i am closing this.. delete the issue ;)
